const SPEED_TOPIC_KEY = 'speed'
const CADENCE_TOPIC_KEY = 'cadence'
const POWER_TOPIC_KEY = 'power'
const HEART_RATE_TOPIC_KEY = 'heartrate'
const RESISTANCE_TOPIC_KEY = 'resistance'
const INCLINE_TOPIC_KEY = 'incline'
const FAN_TOPIC_KEY = 'fan'

const DEVICE_DATA_TOPICS = [
  SPEED_TOPIC_KEY,
  CADENCE_TOPIC_KEY,
  POWER_TOPIC_KEY,
  HEART_RATE_TOPIC_KEY,
  RESISTANCE_TOPIC_KEY,
  INCLINE_TOPIC_KEY,
  FAN_TOPIC_KEY,
]

const DEFAULT_GET_DATA_LIMIT = 10
const GET_DATA_MAX_LIMIT = 500

export {
  SPEED_TOPIC_KEY,
  CADENCE_TOPIC_KEY,
  POWER_TOPIC_KEY,
  HEART_RATE_TOPIC_KEY,
  RESISTANCE_TOPIC_KEY,
  INCLINE_TOPIC_KEY,
  FAN_TOPIC_KEY,
  DEVICE_DATA_TOPICS,
  DEFAULT_GET_DATA_LIMIT,
  GET_DATA_MAX_LIMIT,
}
