const SPEED_TOPIC_KEY = 'speed'
const CADENCE_TOPIC_KEY = 'cadence'
const RESITANCE_TOPIC_KEY = 'resistance'
const INCLINE_TOPIC_KEY = 'incline'

const DEFAULT_GET_DATA_LIMIT = 10
const GET_DATA_MAX_LIMIT = 100

export {
  SPEED_TOPIC_KEY,
  CADENCE_TOPIC_KEY,
  RESITANCE_TOPIC_KEY,
  INCLINE_TOPIC_KEY,
  DEFAULT_GET_DATA_LIMIT,
  GET_DATA_MAX_LIMIT,
}
