const SPEED_TOPIC_KEY = 'speed'
const CADENCE_TOPIC_KEY = 'cadence'
const RESITANCE_TOPIC_KEY = 'resistance'
const INCLINE_TOPIC_KEY = 'incline'

export { SPEED_TOPIC_KEY, CADENCE_TOPIC_KEY, RESITANCE_TOPIC_KEY, INCLINE_TOPIC_KEY }
